/* Flanner service worker — generated by scripts/build_pwa.py, do not edit. */
const CACHE = 'flanner-f524d861cd65';
const SHELL = ["./", "./manifest.webmanifest", "./assets/icons/icon-192.png", "./assets/icons/icon-512.png", "./assets/font/inter-latin.woff2", "./assets/font/robotoflex-latin.woff2"];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys
        .filter(k => k !== CACHE && k !== 'flanner-offline')
        .map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

/* Documents are stale-while-revalidate: a planner opened at a festival should
   paint from cache immediately rather than wait on a flaky connection, and
   pick up any correction on the next visit.

   Assets under assets/ are cache-first. They are content the build replaces
   wholesale rather than edits, and the cache name carries a hash of every
   page, so a deploy that changes one arrives with a new store to put it in.
   Revalidating them would spend a request per font and per basemap on every
   page view to be told each time that nothing had changed. */
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;

  const asset = /\/assets\//.test(new URL(req.url).pathname);

  e.respondWith((async () => {
    const cache = await caches.open(CACHE);
    if (asset) {
      const have = await cache.match(req, {ignoreSearch: true});
      if (have) return have;
      const got = await fetch(req).catch(() => null);
      if (got && got.ok) cache.put(req, got.clone());
      if (got) return got;
      return new Response('', {status: 504});
    }
    /* Read from any Flanner cache, not just this build's. "Save for offline"
       writes from the page, and if it ran before this worker created its own
       store the download would otherwise be invisible here. */
    const hit = await cache.match(req, {ignoreSearch: true}) ||
      await (async () => {
        for (const name of await caches.keys()) {
          if (name === CACHE || !name.startsWith('flanner-')) continue;
          const m = await (await caches.open(name)).match(req, {ignoreSearch: true});
          if (m) return m;
        }
        return null;
      })();
    const live = fetch(req).then(res => {
      if (res && res.ok) cache.put(req, res.clone());
      return res;
    }).catch(() => null);

    if (hit) { e.waitUntil(live); return hit; }
    const res = await live;
    if (res) return res;
    /* Offline and never seen: fall back to the page we do have. */
    return (await cache.match('./')) ||
      new Response('Offline, and this page has not been opened before.',
        {status: 503, headers: {'Content-Type': 'text/plain'}});
  })());
});
