/* Flanner service worker — generated by scripts/build_pwa.py, do not edit. */
const CACHE = 'flanner-51e6c9fa7a68';
const SHELL = ["./", "./manifest.webmanifest", "./assets/icons/icon-192.png", "./assets/icons/icon-512.png"];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

/* Stale-while-revalidate. A planner opened at a festival should paint from
   cache immediately rather than wait on a flaky connection, and pick up any
   correction on the next visit. */
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;

  e.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req, {ignoreSearch: true});
    const live = fetch(req).then(res => {
      if (res && res.ok) cache.put(req, res.clone());
      return res;
    }).catch(() => null);

    if (hit) { e.waitUntil(live); return hit; }
    const res = await live;
    if (res) return res;
    /* Offline and never seen: fall back to the page we do have. */
    return (await cache.match('./')) ||
      new Response('Offline, and this page has not been opened before.',
        {status: 503, headers: {'Content-Type': 'text/plain'}});
  })());
});
