#!/usr/bin/env python3
"""Icons, manifest and service worker — the bits that make Flanner installable.

The pages themselves are already self-contained, so the service worker has an
easy job: there are no sub-resources to juggle, just the HTML documents. It
serves them from cache immediately and refreshes them in the background, which
is the right trade for a planner used in a field with two bars of signal.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

from PIL import Image, ImageDraw

import seo

ROOT = Path(__file__).resolve().parent.parent
ICONS = ROOT / "assets" / "icons"

# Pages the worker precaches on install. Everything else is picked up as it is
# visited, so a first run does not pull six megabytes of planner nobody asked
# for yet.
SHELL = ["./", "./manifest.webmanifest",
         "./assets/icons/icon-192.png", "./assets/icons/icon-512.png"]


def disc(size: int, pad: float = 0.0, bg: str | None = None) -> Image.Image:
    """The Flanner mark: a gradient disc cut on the diagonal, halves pulled apart."""
    s = size * 4
    grad = Image.new("RGB", (s, s))
    px = grad.load()
    ca, cb = (0xB6, 0xFC, 0x46), (0xFF, 0xF2, 0x03)
    for y in range(s):
        for x in range(s):
            t = (x / s * 0.5) + ((s - y) / s * 0.5)
            px[x, y] = tuple(int(ca[i] + (cb[i] - ca[i]) * t) for i in range(3))

    mark = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    for dx, dy, half in ((0.055, -0.083, "up"), (-0.055, 0.083, "dn")):
        mask = Image.new("L", (s, s), 0)
        d = ImageDraw.Draw(mask)
        c, r = s / 2, s * 0.46
        d.ellipse([c + dx * s - r, c + dy * s - r, c + dx * s + r, c + dy * s + r], fill=255)
        cut = Image.new("L", (s, s), 0)
        ImageDraw.Draw(cut).polygon(
            [(-s, c + s * 1.0118), (2 * s, c - s * 1.0118), (2 * s, -s), (-s, -s)], fill=255)
        if half == "dn":
            cut = Image.eval(cut, lambda v: 255 - v)
        mask = Image.composite(mask, Image.new("L", (s, s), 0), cut)
        mark.paste(grad, (0, 0), mask)
    mark = mark.resize((size, size), Image.LANCZOS)

    if pad <= 0 and bg is None:
        return mark
    canvas = Image.new("RGBA", (size, size), bg or (0, 0, 0, 0))
    inner = int(size * (1 - pad * 2))
    off = (size - inner) // 2
    canvas.paste(mark.resize((inner, inner), Image.LANCZOS), (off, off), mark.resize((inner, inner), Image.LANCZOS))
    return canvas


def main() -> None:
    ICONS.mkdir(parents=True, exist_ok=True)
    INK = (16, 16, 16, 255)

    # Plain icons sit on the ink square so the mark reads on any home screen.
    for n in (192, 512):
        disc(n, pad=0.16, bg=INK).save(ICONS / f"icon-{n}.png", optimize=True)
    # A maskable icon may be cropped to a circle, so it needs a wider safe zone.
    disc(512, pad=0.26, bg=INK).save(ICONS / "icon-maskable-512.png", optimize=True)
    # Apple ignores maskable and does not round transparent corners itself.
    disc(180, pad=0.16, bg=INK).save(ICONS / "apple-touch-icon.png", optimize=True)
    print(f"  icons → {len(list(ICONS.glob('*.png')))} files")

    manifest = {
        "id": "/kallioblockpartyplanner/",
        "name": "Flanner — Helsinki festival planner",
        "short_name": "Flanner",
        "description": "Plannable timetables for Helsinki festivals. Works offline.",
        "start_url": "./",
        "scope": "./",
        "display": "standalone",
        "orientation": "any",
        "lang": "en",
        "dir": "ltr",
        "background_color": "#e9e9e9",
        "theme_color": "#e9e9e9",
        "categories": ["music", "entertainment", "travel"],
        "icons": [
            {"src": "assets/icons/icon-192.png", "sizes": "192x192", "type": "image/png"},
            {"src": "assets/icons/icon-512.png", "sizes": "512x512", "type": "image/png"},
            {"src": "assets/icons/icon-maskable-512.png", "sizes": "512x512",
             "type": "image/png", "purpose": "maskable"},
        ],
        "shortcuts": [
            {"name": "Flow Festival", "url": "flow/"},
            {"name": "Kallio Block Party", "url": "kallio/"},
        ],
    }
    (ROOT / "manifest.webmanifest").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")

    # The cache name carries a hash of every built page, so a deploy that
    # changes any of them retires the old cache instead of serving it forever.
    stamp = hashlib.sha256()
    for page in ("index.html", "kallio/index.html", "flow/index.html",
                 "about/index.html", "terms/index.html", "privacy/index.html"):
        f = ROOT / page
        if f.exists():
            stamp.update(f.read_bytes())
    version = stamp.hexdigest()[:12]

    sw = f"""/* Flanner service worker — generated by scripts/build_pwa.py, do not edit. */
const CACHE = 'flanner-{version}';
const SHELL = {json.dumps(SHELL)};

self.addEventListener('install', e => {{
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)).then(() => self.skipWaiting()));
}});

self.addEventListener('activate', e => {{
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys
        .filter(k => k !== CACHE && k !== 'flanner-offline')
        .map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
}});

/* Stale-while-revalidate. A planner opened at a festival should paint from
   cache immediately rather than wait on a flaky connection, and pick up any
   correction on the next visit. */
self.addEventListener('fetch', e => {{
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;

  e.respondWith((async () => {{
    const cache = await caches.open(CACHE);
    /* Read from any Flanner cache, not just this build's. "Save for offline"
       writes from the page, and if it ran before this worker created its own
       store the download would otherwise be invisible here. */
    const hit = await cache.match(req, {{ignoreSearch: true}}) ||
      await (async () => {{
        for (const name of await caches.keys()) {{
          if (name === CACHE || !name.startsWith('flanner-')) continue;
          const m = await (await caches.open(name)).match(req, {{ignoreSearch: true}});
          if (m) return m;
        }}
        return null;
      }})();
    const live = fetch(req).then(res => {{
      if (res && res.ok) cache.put(req, res.clone());
      return res;
    }}).catch(() => null);

    if (hit) {{ e.waitUntil(live); return hit; }}
    const res = await live;
    if (res) return res;
    /* Offline and never seen: fall back to the page we do have. */
    return (await cache.match('./')) ||
      new Response('Offline, and this page has not been opened before.',
        {{status: 503, headers: {{'Content-Type': 'text/plain'}}}});
  }})());
}});
"""
    (ROOT / "sw.js").write_text(sw)
    print(f"  manifest.webmanifest · sw.js (cache flanner-{version})")


if __name__ == "__main__":
    print(ROOT)
    main()
