#!/usr/bin/env python3
"""Read a festival's colour off the picture the festival publishes of itself.

`accent` in `data/festivals.json` is the one value a festival's whole theme is
made from — its card here, its highlight, its bar in the calendar and every
surface of its planner. Only the hue and the chroma travel: the lightness ramp
is Material's, generated by `m3color`. So what this has to find is not a pixel
but a *hue family* — the colour someone would name if you asked them what
colour the poster is.

Which is why it does not take the commonest palette entry. A printed poster is
rarely flat: the Helsinki Festival's is a gradient running orange to magenta,
which median-cut splits into a dozen entries that then lose a vote to one flat
patch of teal covering a fifth of the area. Binning by hue puts the gradient
back together, and the family with the most of the picture in it wins.

Discarded before any of that: the near-white of paper and line work, the
near-black of ink, and anything too grey to be a hue at all. A festival whose
picture is genuinely achromatic has no colour to read, and this says so rather
than returning a muddy one.

    python3 scripts/promocolor.py              # every festival with a picture
    python3 scripts/promocolor.py juhlaviikot  # one, with its runners-up
"""
from __future__ import annotations

import io
import json
import math
import pathlib
import sys

from PIL import Image

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import m3color
from assets import ROOT

# The paper and the line work at one end, the ink at the other. Both are in
# every printed poster and neither is its colour.
LIGHT_MAX = 88.0
DARK_MIN = 12.0
# Below this a colour is a grey with a cast, and naming it a hue is a guess.
CHROMA_MIN = 15.0
# The band an accent has to sit in to be one. A family can cover most of a
# picture and still be no use as a theme: Blockfest's key visual is three
# quarters night sky, and that sky is a violet at tone 21 — the colour a dark
# room is, which is to say the picture's ink rather than its colour. Painted on
# a card at the tones Material asks for, it would arrive as the same violet the
# two film festivals already carry, and the point of a festival having its own
# colour is that it is telling itself apart from the others. So the accent is
# the fullest family that could be painted; anything darker or paler is still
# reported, because it is really in the picture, and `ink` is where the dark
# end of it belongs.
ACCENT_L = (25.0, 85.0)
# 24 bins, and each family is read with its neighbours so a hue sitting on a
# boundary is not split in half by where the bins happen to fall.
BINS = 24
# Enough pixels to be representative, few enough to be instant. Sampled rather
# than averaged: averaging a splatter print blends the paper into the paint and
# invents colours that are nowhere in it.
SAMPLE = 320


def _lab(r: int, g: int, b: int) -> tuple[float, float, float]:
    """sRGB bytes to CIELAB, by the same maths m3color uses for a hex."""
    return m3color.hex_to_lab("#%02x%02x%02x" % (r, g, b))


def _hex(L: float, a: float, b: float) -> str:
    r, g, bl = m3color.lab_to_rgb(L, a, b)
    return "#%02x%02x%02x" % (round(r * 255), round(g * 255), round(bl * 255))


def families(path: pathlib.Path) -> list[dict]:
    """Every hue family in the picture, the most of it first.

    A family is named by three numbers, and none of them is a plain average.

    The hue is the circular mean, weighted by how much of the picture each
    pixel is — the direction the family points.

    The chroma is a high percentile, not the mean. A family spans a range of
    hues, and averaging colour vectors that point slightly apart cancels some
    of their length: take the mean of the Helsinki Festival's reds and a poster
    of vivid vermilion reports as terracotta. The ramp that Material builds
    from this never claims more chroma than the source, so a source flattened
    by its own averaging makes a theme duller than the picture it came from.
    The 85th percentile is what the picture is at its most itself, which is
    what a poster is designed to be read as.

    The lightness is the median, which is the one an average does no harm to.
    """
    img = Image.open(path).convert("RGB")
    img.thumbnail((SAMPLE, SAMPLE), Image.Resampling.NEAREST)
    bins: list[list[tuple[float, float, float]]] = [[] for _ in range(BINS)]
    kept = 0
    for r, g, b in img.getdata():
        L, A, B = _lab(r, g, b)
        if L >= LIGHT_MAX or L <= DARK_MIN:
            continue
        c = math.hypot(A, B)
        if c < CHROMA_MIN:
            continue
        kept += 1
        h = math.degrees(math.atan2(B, A)) % 360
        bins[int(h / (360 / BINS))].append((L, c, h))
    if not kept:
        return []
    out = []
    for i, s in enumerate(bins):
        if not s:
            continue
        # Read with its neighbours, so the family is the family and not the bin.
        near = s + bins[(i - 1) % BINS] + bins[(i + 1) % BINS]
        n = len(near)
        # Circular, because a family sitting on 0° has pixels at 359 and at 1.
        x = sum(math.cos(math.radians(p[2])) for p in near) / n
        y = sum(math.sin(math.radians(p[2])) for p in near) / n
        hue = math.degrees(math.atan2(y, x)) % 360
        chroma = sorted(p[1] for p in near)[int(n * .85) - 1 if n > 1 else 0]
        L = sorted(p[0] for p in near)[n // 2]
        out.append({"share": n / kept, "peak": len(s) / kept,
                    "hex": m3color.tone(hue, chroma, L),
                    "L": L, "C": chroma, "h": hue})
    # One entry per family, not one per bin: neighbouring bins of the same
    # family all report nearly the same colour, so the fullest bin speaks for
    # it and the ones leaning on it are dropped.
    out.sort(key=lambda f: -f["peak"])
    picked: list[dict] = []
    for f in out:
        if all(_apart(f["h"], p["h"]) >= 360 / BINS * 1.5 for p in picked):
            picked.append(f)
    picked.sort(key=lambda f: -f["share"])
    return picked


def _apart(h1: float, h2: float) -> float:
    d = abs(h1 - h2) % 360
    return min(d, 360 - d)


def accent(path: pathlib.Path) -> str | None:
    """The fullest family a card could actually be drawn in."""
    for f in families(path):
        if ACCENT_L[0] <= f["L"] <= ACCENT_L[1]:
            return f["hex"]
    return None


def ink(accent_hex: str) -> str:
    """The dark end of the same colour, which is how every record states it.

    Same hue at tone 20 with half the chroma — dark enough to print text of,
    still recognisably the festival's own rather than a black.
    """
    L, a, b = m3color.hex_to_lab(accent_hex)
    hue = math.degrees(math.atan2(b, a)) % 360
    return m3color.tone(hue, math.hypot(a, b) / 2, 20)


def main() -> None:
    cfg = json.load(io.open(ROOT / "data" / "festivals.json", encoding="utf-8"))
    fs = cfg["festivals"] if isinstance(cfg, dict) else cfg
    want = sys.argv[1] if len(sys.argv) > 1 else None
    for f in fs:
        if want and f["id"] != want:
            continue
        if not f.get("promo"):
            continue
        path = ROOT / "assets" / "home" / f["promo"]
        fam = families(path)
        if not fam:
            print(f"{f['id']:<12} {f['promo']} — no colour in it")
            continue
        top = next((x for x in fam if ACCENT_L[0] <= x["L"] <= ACCENT_L[1]), None)
        print(f"{f['id']:<12} {f['promo']}")
        print(f"  record  accent {f.get('accent')}  ink {f.get('ink')}")
        if not top:
            print("  picture nothing in it a card could be drawn in")
            continue
        print(f"  picture accent {top['hex']}  ink {ink(top['hex'])}"
              f"   {top['share'] * 100:.0f}% of the colour, "
              f"h{top['h']:.0f} C{top['C']:.0f} L{top['L']:.0f}")
        for other in (fam if want else []):
            if other is top:
                continue
            why = "" if ACCENT_L[0] <= other["L"] <= ACCENT_L[1] else "  (too dark to paint)" \
                if other["L"] < ACCENT_L[0] else "  (too pale to paint)"
            print(f"          also {other['hex']}  {other['share'] * 100:5.1f}%  "
                  f"h{other['h']:.0f} C{other['C']:.0f} L{other['L']:.0f}{why}")


if __name__ == "__main__":
    main()
